version: "3.8"

services:
  mogodb-service:
    image: mongo:latest
    container_name: mogodb-service
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: alfan
      MONGO_INITDB_ROOT_PASSWORD: alfan
      MONGO_INITDB_DATABASE: admin
    networks:
      - network_alfan

  mogodb-express-service:
    image: mongo-express:latest
    container_name: mogodb-express-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: alfan
      ME_CONFIG_MONGODB_ADMINPASSWORD: alfan
      ME_CONFIG_MONGODB_SERVER: mogodb-service
    networks:
      - network_alfan
    depends_on:
      - mogodb-service

networks:
  network_alfan:
    name: network_alfan
    driver: bridge
