version: "3.8"

services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: alfan
      MONGO_INITDB_ROOT_PASSWORD: alfan
      MONGO_INITDB_DATABASE: alfan
    volumes:
      - type: bind
        source: "./data-mongo1"
        target: "/data/db"
        read_only: false
