version: "3.8"

services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: khannedy
      MONGO_INITDB_ROOT_PASSWORD: khannedy
      MONGO_INITDB_DATABASE: admin
    volumes:
      - type: volume
        source: mongo-data1
        target: "/data/db"
        read_only: false
  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: alfan
      MONGO_INITDB_ROOT_PASSWORD: alfan
      MONGO_INITDB_DATABASE: admin
    volumes:
      - type: volume
        source: mongo-data2
        target: "/data/db"
        read_only: false

networks:
  network_alfan:
    name: network_alfan
    driver: bridge

volumes:
  mongo-data1:
    name: mongo-data1
  mongo-data2:
    name: mongo-data2
    
